### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by nick-youngblut** [braingeneers/SIMS#3]
Where are the pretrained models from [the paper](https://www.cell.com/cell-genomics/fulltext/S2666-979X(24)00165-4) and available via the [streamlit app](https://sc-sims-app.streamlit.app/)?

I can't find any mention of them in this repo.

**Comment by JesusGF1** [comment]
Hi Nick,
sorry for the late response. The pretrained models together with the web application can be found in this [repo](https://github.com/JesusGF1/sims_app) .

**Comment by nick-youngblut** [comment]
Thanks @JesusGF1 for clarifying!
